package vn.iotstar.controller;
import java.io.IOException;
import org.springframework.data.domain.*;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;
import vn.iotstar.entity.*;
import vn.iotstar.repository.*;
import vn.iotstar.service.UploadService;
import vn.iotstar.service.AuthService;
@Controller @RequestMapping("/admin") public class AdminController {
 private final CategoryRepository categories; private final ProductRepository products; private final UserRepository users; private final UploadService uploads; private final AuthService auth;
 public AdminController(CategoryRepository c,ProductRepository p,UserRepository u,UploadService up,AuthService auth){categories=c;products=p;users=u;uploads=up;this.auth=auth;}
 private Pageable page(int page){return PageRequest.of(Math.max(0,page-1),10,Sort.by("categoryId").descending());}
 @GetMapping({"","/"}) public String dashboard(Model m){m.addAttribute("categoryCount",categories.count());m.addAttribute("productCount",products.count());m.addAttribute("userCount",users.count());return "admin/dashboard";}
 @GetMapping("/categories") public String categories(@RequestParam(defaultValue="") String keyword,@RequestParam(required=false) Integer status,@RequestParam(defaultValue="1") int page,Model m){Page<Category> data=status==null?categories.findByCategorynameContainingIgnoreCase(keyword,page(page)):categories.findByCategorynameContainingIgnoreCaseAndStatus(keyword,status,page(page));m.addAttribute("data",data);m.addAttribute("keyword",keyword);m.addAttribute("status",status);return "admin/category-list";}
 @GetMapping("/categories/new") public String categoryNew(Model m){m.addAttribute("category",new Category());return "admin/category-form";}
 @PostMapping("/categories/save") public String categorySave(@RequestParam(required=false) Integer id,@RequestParam String categoryname,@RequestParam int status,@RequestParam(required=false) String imageUrl,@RequestParam(required=false) MultipartFile imageFile,RedirectAttributes ra) throws IOException {Category c=id==null?new Category():categories.findById(id).orElseThrow();if(categories.existsByCategorynameIgnoreCaseAndCategoryIdNot(categoryname,id==null?-1:id)){ra.addFlashAttribute("error","Tên danh mục đã tồn tại.");return id==null?"redirect:/admin/categories/new":"redirect:/admin/categories/"+id+"/edit";}c.setCategoryname(categoryname.trim());c.setStatus(status);String file=uploads.save(imageFile);if(file!=null){uploads.deleteLocal(c.getImages());c.setImages(file);}else if(imageUrl!=null&&!imageUrl.isBlank())c.setImages(imageUrl.trim());categories.save(c);ra.addFlashAttribute("message","Đã lưu danh mục.");return "redirect:/admin/categories";}
 @GetMapping("/categories/{id}/edit") public String categoryEdit(@PathVariable int id,Model m){m.addAttribute("category",categories.findById(id).orElseThrow());return "admin/category-form";}
 @PostMapping("/categories/{id}/delete") public String categoryDelete(@PathVariable int id,RedirectAttributes ra){if(products.countByCategory_CategoryId(id)>0)ra.addFlashAttribute("error","Không thể xóa danh mục đang có sản phẩm.");else {categories.deleteById(id);ra.addFlashAttribute("message","Đã xóa danh mục.");}return "redirect:/admin/categories";}
 @GetMapping("/products") public String products(@RequestParam(defaultValue="") String keyword,@RequestParam(required=false) Integer status,@RequestParam(defaultValue="1") int page,Model m){Pageable pg=PageRequest.of(Math.max(0,page-1),10,Sort.by("productId").descending());m.addAttribute("data",status==null?products.findByProductNameContainingIgnoreCase(keyword,pg):products.findByProductNameContainingIgnoreCaseAndStatus(keyword,status,pg));m.addAttribute("keyword",keyword);m.addAttribute("status",status);return "admin/product-list";}
 @GetMapping("/products/new") public String productNew(Model m){m.addAttribute("product",new Product());m.addAttribute("categories",categories.findAll());return "admin/product-form";}
 @GetMapping("/products/{id}/edit") public String productEdit(@PathVariable int id,Model m){m.addAttribute("product",products.findById(id).orElseThrow());m.addAttribute("categories",categories.findAll());return "admin/product-form";}
 @PostMapping("/products/save") public String productSave(@RequestParam(required=false) Integer id,@RequestParam String productName,@RequestParam String description,@RequestParam double price,@RequestParam int stock,@RequestParam int status,@RequestParam int categoryId,@RequestParam(required=false) MultipartFile imageFile,RedirectAttributes ra) throws IOException {Product p=id==null?new Product():products.findById(id).orElseThrow();p.setProductName(productName);p.setDescription(description);p.setPrice(price);p.setStock(stock);p.setStatus(status);p.setCategory(categories.findById(categoryId).orElseThrow());String f=uploads.save(imageFile);if(f!=null){if(p.getProductImages()!=null && !p.getProductImages().isEmpty()){uploads.deleteLocal(p.getProductImages().get(0).getImagePath());p.getProductImages().clear();} p.getProductImages().add(new vn.iotstar.entity.ProductImage(f, p));}products.save(p);ra.addFlashAttribute("message","Đã lưu sản phẩm.");return "redirect:/admin/products";}
 @PostMapping("/products/{id}/delete") public String productDelete(@PathVariable int id,RedirectAttributes ra){products.deleteById(id);ra.addFlashAttribute("message","Đã xóa sản phẩm.");return "redirect:/admin/products";}
 @GetMapping("/users") public String users(@RequestParam(defaultValue="") String keyword,@RequestParam(required=false) Integer role,@RequestParam(required=false) Integer status,@RequestParam(defaultValue="1") int page,Model m){var spec=org.springframework.data.jpa.domain.Specification.<User>where((r,q,b)->b.or(b.like(b.lower(r.get("username")),"%"+keyword.toLowerCase()+"%"),b.like(b.lower(r.get("email")),"%"+keyword.toLowerCase()+"%"),b.like(b.lower(r.get("fullname")),"%"+keyword.toLowerCase()+"%"))).and(role==null?null:(r,q,b)->b.equal(r.get("role"),role)).and(status==null?null:(r,q,b)->b.equal(r.get("status"),status));m.addAttribute("data",users.findAll(spec,PageRequest.of(Math.max(0,page-1),10,Sort.by("id").descending())));m.addAttribute("keyword",keyword);m.addAttribute("role",role);m.addAttribute("status",status);return "admin/user-list";}
 @GetMapping("/users/{id}/edit") public String userEdit(@PathVariable int id,Model m){m.addAttribute("managedUser",users.findById(id).orElseThrow());return "admin/user-form";}
 @GetMapping("/users/new") public String userNew(){return "admin/user-new";}
 @PostMapping("/users/new") public String userCreate(@RequestParam String username,@RequestParam String email,@RequestParam String fullname,@RequestParam String password,@RequestParam(required=false) String phone,@RequestParam int role,@RequestParam int status,RedirectAttributes ra){try{auth.createByAdmin(username,email,password,fullname,phone,role,status);ra.addFlashAttribute("message","Đã tạo người dùng.");return "redirect:/admin/users";}catch(IllegalArgumentException e){ra.addFlashAttribute("error",e.getMessage());return "redirect:/admin/users/new";}}
 @PostMapping("/users/{id}/save") public String userSave(@PathVariable int id,@RequestParam String username,@RequestParam String email,@RequestParam String fullname,@RequestParam(required=false) String phone,@RequestParam int role,@RequestParam int status,@RequestParam(required=false) String password,@AuthenticationPrincipal UserDetails principal,RedirectAttributes ra){User u=users.findById(id).orElseThrow();if(users.existsByEmailIgnoreCaseAndIdNot(email,id)||users.existsByUsernameIgnoreCaseAndIdNot(username,id)){ra.addFlashAttribute("error","Email hoặc tên đăng nhập đã tồn tại.");return "redirect:/admin/users/"+id+"/edit";}u.setUsername(username);u.setEmail(email);u.setFullname(fullname);u.setPhone(phone);if(!u.getEmail().equals(principal.getUsername())){u.setRole(role);u.setStatus(status);}users.save(u);ra.addFlashAttribute("message","Đã cập nhật người dùng.");return "redirect:/admin/users";}
 @PostMapping("/users/{id}/lock") public String lockUser(@PathVariable int id,@AuthenticationPrincipal UserDetails principal,RedirectAttributes ra){User u=users.findById(id).orElseThrow();if(u.getEmail().equals(principal.getUsername()))ra.addFlashAttribute("error","Bạn không thể khóa chính mình.");else {u.setStatus(0);users.save(u);ra.addFlashAttribute("message","Đã khóa tài khoản.");}return "redirect:/admin/users";}
}
